<!-- value="source,location,type,account" -->
 <option value="">wähle einen Radiosender...</option>
 <option value="TUNEIN,/v1/playback/station/s6814  ,stationurl,"    >Radio Swiss Jazz</option>
 <option value="TUNEIN,/v1/playback/station/s10614 ,stationurl,"    >Radio-Jazz</option>
 <option value="TUNEIN,/v1/playback/station/s49695 ,stationurl,"    >GotRadio Jazz So Smooth</option>
 <option value="TUNEIN,/v1/playback/station/s25582 ,stationurl,"    >Radio Swiss Classic</option>
 <option value="TUNEIN,/v1/playback/station/s31824 ,stationurl,"    >All-Classical-Portland</option>
 <option value="TUNEIN,/v1/playback/station/s95144 ,stationurl,"    >Venice-Classic-Radio</option>
 <option value="TUNEIN,/v1/playback/station/s25028 ,stationurl,"    >Klassik-Radio</option>
 <option value="TUNEIN,/v1/playback/station/s183588,stationurl,"    >Aardvark Blues FM</option>
 <option value="TUNEIN,/v1/playback/station/s200813,stationurl,"    >1jazz.ru - Blues</option>
 <option value="TUNEIN,/v1/playback/station/s255678,stationurl,"    >Blues Radio</option>
 <option value="TUNEIN,/v1/playback/station/s49671 ,stationurl,"    >GotRadio Bit O Blues</option>
 <option value="TUNEIN,/v1/playback/station/s49682 ,stationurl,"    >GotRadio Folklore</option>
 <option value="TUNEIN,/v1/playback/station/s49678 ,stationurl,"    >GotRadio Todays Country</option>
 <option value="TUNEIN,/v1/playback/station/s99894 ,stationurl,"    >Country-Radio-Switzerland</option>
 <option value="TUNEIN,/v1/playback/station/s116266,stationurl,"    >Irish Pub Radio</option>
 <option value="TUNEIN,/v1/playback/station/s306601,stationurl,"    >Irish Folk</option>
 <option value="TUNEIN,/v1/playback/station/s17895 ,stationurl,"    >live Ireland</option>
 <option value="TUNEIN,/v1/playback/station/s152606,stationurl,"    >All Irish Radio</option>
 <option value="TUNEIN,/v1/playback/station/s65668 ,stationurl,"    >GotRadio Celtic Crossing</option>
 <option value="TUNEIN,/v1/playback/station/s101189,stationurl,"    >Radio-Celtic-Sounds</option>
 <option value="TUNEIN,/v1/playback/station/s244590,stationurl,"    >MacSlons-Irish-Pub-Radio</option>
 <option value="TUNEIN,/v1/playback/station/s269960,stationurl,"    >Reggaeton Radio FM</option>
 <option value="TUNEIN,/v1/playback/station/s49691 ,stationurl,"    >GotRadio Reggae</option>
 <option value="TUNEIN,/v1/playback/station/s2469  ,stationurl,"    >Latina</option>
 <option value="TUNEIN,/v1/playback/station/s95277 ,stationurl,"    >LATINO</option>
 <option value="TUNEIN,/v1/playback/station/s25243 ,stationurl,"    >Radio Swiss Pop</option>
 <option value="TUNEIN,/v1/playback/station/s8514  ,stationurl,"    >Österreich 1</option>
 <option value="TUNEIN,/v1/playback/station/s26058 ,stationurl,"    >ORF Radio Steiermark</option>
 <option value="TUNEIN,/v1/playback/station/s8007  ,stationurl,"    >OE3 Hitradio</option>
 <option value="TUNEIN,/v1/playback/station/s8235  ,stationurl,"    >Radio FM4</option>
 <option value="TUNEIN,/v1/playback/station/s149491,stationurl,"    >Welle 1 Graz</option>
 <option value="TUNEIN,/v1/playback/station/s1139  ,stationurl,"    >Antenne Steiermark</option>
 <option value="TUNEIN,/v1/playback/station/s15532 ,stationurl,"    >KRONEHIT Radio</option>
 <option value="TUNEIN,/v1/playback/station/s11109 ,stationurl,"    >Radio-Klassik-Stephansdom</option>
 <option value="TUNEIN,/v1/playback/station/s25852 ,stationurl,"    >Das-Soundportal-Radio</option>
 <option value="TUNEIN,/v1/playback/station/s177755,stationurl,"    >Lounge-FM-Digital</option>
 <option value="TUNEIN,/v1/playback/station/s68932 ,stationurl,"    >Lounge-FM Wien</option>
 <option value="TUNEIN,/v1/playback/station/s302526,stationurl,"    >Antenne Christmas Hits</option>
 <option value="TUNEIN,/v1/playback/station/s184676,stationurl,"    >The Christmas Station</option>
 <option value="TUNEIN,/v1/playback/station/s302001,stationurl,"    >Radio Christmas</option>
 <option value="TUNEIN,/v1/playback/station/s280136,stationurl,"    >All Christmas Hits </option>
 <option value="AMAZON,catalog/stations/A3OP0QYHMSL4V2/#playable,tracklist,michael.sproger@gmx.at">Weihnachts-Oldies</option>
 <option value="AMAZON,catalog/stations/A2ZXT6GX0QQH5B/#playable,tracklist,michael.sproger@gmx.at">Swinging Christmas</option>

